server:
  port: 8080

spring:
  application:
    name: T1Academy_task03

  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: tx.
